# -*- coding: utf-8 -*-
"""KV_cache_implementation_comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XlbcDkf9JZ8YUJeFbKkdLKXbG6l4oxjW

KV Cache Implementation Benchmark: torch.cat vs Pre-allocated Buffers

This script benchmarks two KV cache implementations during autoregressive decoding:
1. Inefficient: Using torch.cat to grow the cache each step (repeated allocation + copy)
2. Efficient: Using pre-allocated buffers with slice assignment (no allocation during decode)

Run on Google Colab with GPU runtime for best results.
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import math
import time
import matplotlib.pyplot as plt
from typing import Optional, Tuple

# Check for GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")
if device.type == "cuda":
    print(f"GPU: {torch.cuda.get_device_name(0)}")

class MultiHeadAttentionCatCache(nn.Module):
    """KV Cache using torch.cat — allocates new memory every decode step."""

    def __init__(self, d_model: int, n_heads: int):
        super().__init__()
        self.d_model = d_model
        self.n_heads = n_heads
        self.d_h = d_model // n_heads

        self.W_q = nn.Linear(d_model, d_model, bias=False)
        self.W_k = nn.Linear(d_model, d_model, bias=False)
        self.W_v = nn.Linear(d_model, d_model, bias=False)
        self.W_o = nn.Linear(d_model, d_model, bias=False)

        self.k_cache: Optional[torch.Tensor] = None
        self.v_cache: Optional[torch.Tensor] = None

    def reset_cache(self):
        self.k_cache = None
        self.v_cache = None

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        B, seq_len, _ = x.shape

        Q = self.W_q(x).view(B, seq_len, self.n_heads, self.d_h).transpose(1, 2)
        K = self.W_k(x).view(B, seq_len, self.n_heads, self.d_h).transpose(1, 2)
        V = self.W_v(x).view(B, seq_len, self.n_heads, self.d_h).transpose(1, 2)

        # Inefficient: torch.cat creates new tensor and copies existing cache
        if self.k_cache is None:
            self.k_cache = K
            self.v_cache = V
        else:
            self.k_cache = torch.cat([self.k_cache, K], dim=2)
            self.v_cache = torch.cat([self.v_cache, V], dim=2)

        K_full = self.k_cache
        V_full = self.v_cache

        scores = torch.matmul(Q, K_full.transpose(-2, -1)) / math.sqrt(self.d_h)
        attn_weights = F.softmax(scores, dim=-1)
        output = torch.matmul(attn_weights, V_full)

        output = output.transpose(1, 2).contiguous().view(B, seq_len, self.d_model)
        return self.W_o(output)


class MultiHeadAttentionPreallocCache(nn.Module):
    """KV Cache using pre-allocated buffers — no allocation during decode."""

    def __init__(self, d_model: int, n_heads: int, max_seq_len: int):
        super().__init__()
        self.d_model = d_model
        self.n_heads = n_heads
        self.d_h = d_model // n_heads
        self.max_seq_len = max_seq_len

        self.W_q = nn.Linear(d_model, d_model, bias=False)
        self.W_k = nn.Linear(d_model, d_model, bias=False)
        self.W_v = nn.Linear(d_model, d_model, bias=False)
        self.W_o = nn.Linear(d_model, d_model, bias=False)

        # Pre-allocated cache buffers — no allocation during decode
        self.register_buffer('k_cache', torch.zeros(1, n_heads, max_seq_len, self.d_h))
        self.register_buffer('v_cache', torch.zeros(1, n_heads, max_seq_len, self.d_h))
        self.cache_position = 0

    def reset_cache(self):
        self.k_cache.zero_()
        self.v_cache.zero_()
        self.cache_position = 0

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        B, seq_len, _ = x.shape

        Q = self.W_q(x).view(B, seq_len, self.n_heads, self.d_h).transpose(1, 2)
        K = self.W_k(x).view(B, seq_len, self.n_heads, self.d_h).transpose(1, 2)
        V = self.W_v(x).view(B, seq_len, self.n_heads, self.d_h).transpose(1, 2)

        # Efficient: write directly to pre-allocated buffer (no allocation)
        start = self.cache_position
        end = self.cache_position + seq_len
        self.k_cache[:, :, start:end, :] = K
        self.v_cache[:, :, start:end, :] = V
        self.cache_position = end

        K_full = self.k_cache[:, :, :end, :]
        V_full = self.v_cache[:, :, :end, :]

        scores = torch.matmul(Q, K_full.transpose(-2, -1)) / math.sqrt(self.d_h)
        attn_weights = F.softmax(scores, dim=-1)
        output = torch.matmul(attn_weights, V_full)

        output = output.transpose(1, 2).contiguous().view(B, seq_len, self.d_model)
        return self.W_o(output)

def copy_weights(src: nn.Module, dst: nn.Module):
    """Copy weights from src to dst to ensure fair comparison."""
    dst.W_q.weight.data.copy_(src.W_q.weight.data)
    dst.W_k.weight.data.copy_(src.W_k.weight.data)
    dst.W_v.weight.data.copy_(src.W_v.weight.data)
    dst.W_o.weight.data.copy_(src.W_o.weight.data)


def benchmark_decode(
    model: nn.Module,
    num_decode_steps: int,
    d_model: int,
    batch_size: int = 1,
    warmup_steps: int = 10
) -> float:
    """
    Benchmark autoregressive decoding.

    Returns total time for num_decode_steps decode iterations (excluding warmup).
    """
    model.eval()
    model.reset_cache()

    with torch.no_grad():
        # Warmup: run a few steps to stabilize CUDA kernels
        for _ in range(warmup_steps):
            x = torch.randn(batch_size, 1, d_model, device=device)
            _ = model(x)

        # Reset cache for actual benchmark
        model.reset_cache()
        torch.cuda.synchronize()

        start_time = time.perf_counter()

        for _ in range(num_decode_steps):
            x = torch.randn(batch_size, 1, d_model, device=device)
            _ = model(x)

        torch.cuda.synchronize()
        end_time = time.perf_counter()

    return end_time - start_time


def run_benchmark(
    context_lengths: list[int],
    d_model: int = 1024,
    n_heads: int = 16,
    batch_size: int = 1,
    num_runs: int = 3
) -> Tuple[list[float], list[float]]:
    """
    Run benchmarks across different context lengths.

    Returns (cat_times, prealloc_times) — averaged over num_runs.
    """
    max_ctx = max(context_lengths)

    # Initialize models
    model_cat = MultiHeadAttentionCatCache(d_model, n_heads).to(device)
    model_prealloc = MultiHeadAttentionPreallocCache(d_model, n_heads, max_ctx).to(device)

    # Copy weights for fair comparison
    copy_weights(model_cat, model_prealloc)

    cat_times = []
    prealloc_times = []

    for ctx_len in context_lengths:
        print(f"Benchmarking context length: {ctx_len}")

        cat_run_times = []
        prealloc_run_times = []

        for run in range(num_runs):
            # Benchmark torch.cat implementation
            t_cat = benchmark_decode(model_cat, ctx_len, d_model, batch_size)
            cat_run_times.append(t_cat)

            # Benchmark pre-allocated implementation
            t_prealloc = benchmark_decode(model_prealloc, ctx_len, d_model, batch_size)
            prealloc_run_times.append(t_prealloc)

        # Average over runs
        cat_times.append(sum(cat_run_times) / num_runs)
        prealloc_times.append(sum(prealloc_run_times) / num_runs)

        speedup = cat_times[-1] / prealloc_times[-1]
        print(f"  torch.cat: {cat_times[-1]*1000:.2f} ms, "
              f"pre-alloc: {prealloc_times[-1]*1000:.2f} ms, "
              f"speedup: {speedup:.2f}x")

    return cat_times, prealloc_times

def plot_results(
    context_lengths: list[int],
    cat_times: list[float],
    prealloc_times: list[float],
    d_model: int,
    n_heads: int
):
    """Generate visualization of benchmark results."""
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    # Convert to milliseconds
    cat_ms = [t * 1000 for t in cat_times]
    prealloc_ms = [t * 1000 for t in prealloc_times]
    speedups = [c / p for c, p in zip(cat_times, prealloc_times)]

    # Plot 1: Absolute times
    ax1 = axes[0]
    ax1.plot(context_lengths, cat_ms, 'o-', label='torch.cat (inefficient)',
             color='#e74c3c', linewidth=2, markersize=8)
    ax1.plot(context_lengths, prealloc_ms, 's-', label='Pre-allocated buffer (efficient)',
             color='#27ae60', linewidth=2, markersize=8)
    ax1.set_xlabel('Context Length (tokens)', fontsize=12)
    ax1.set_ylabel('Total Decode Time (ms)', fontsize=12)
    ax1.set_title(f'KV Cache Decode Time vs Context Length\n(d_model={d_model}, n_heads={n_heads})',
                  fontsize=13)
    ax1.legend(fontsize=11)
    ax1.grid(True, alpha=0.3)
    ax1.set_xlim(left=0)
    ax1.set_ylim(bottom=0)

    # Plot 2: Speedup factor
    ax2 = axes[1]
    bars = ax2.bar(range(len(context_lengths)), speedups, color='#3498db', alpha=0.8)
    ax2.axhline(y=1.0, color='#e74c3c', linestyle='--', linewidth=1.5, label='No speedup')
    ax2.set_xlabel('Context Length (tokens)', fontsize=12)
    ax2.set_ylabel('Speedup Factor (torch.cat / pre-alloc)', fontsize=12)
    ax2.set_title('Speedup from Pre-allocated KV Cache', fontsize=13)
    ax2.set_xticks(range(len(context_lengths)))
    ax2.set_xticklabels(context_lengths)
    ax2.legend(fontsize=11)
    ax2.grid(True, alpha=0.3, axis='y')

    # Add value labels on bars
    for bar, speedup in zip(bars, speedups):
        height = bar.get_height()
        ax2.annotate(f'{speedup:.2f}x',
                     xy=(bar.get_x() + bar.get_width() / 2, height),
                     xytext=(0, 3),
                     textcoords="offset points",
                     ha='center', va='bottom', fontsize=10)

    plt.tight_layout()
    plt.savefig('kv_cache_benchmark.png', dpi=150, bbox_inches='tight')
    plt.show()
    print("\nPlot saved to 'kv_cache_benchmark.png'")

def plot_scaling_analysis(
    context_lengths: list[int],
    cat_times: list[float],
    prealloc_times: list[float]
):
    """Analyze whether difference scales quadratically."""
    import numpy as np

    ctx = np.array(context_lengths)
    diff = np.array(cat_times) - np.array(prealloc_times)

    # Fit: diff = c * N^2
    # log(diff) = log(c) + 2*log(N)
    log_ctx = np.log(ctx)
    log_diff = np.log(diff)

    # Linear regression in log-log space
    slope, intercept = np.polyfit(log_ctx, log_diff, 1)

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    # Plot 1: Difference vs N^2
    ax1 = axes[0]
    ax1.plot(ctx**2, diff * 1000, 'o-', color='#9b59b6', linewidth=2, markersize=8)
    ax1.set_xlabel('Context Length² (N²)', fontsize=12)
    ax1.set_ylabel('Time Difference (ms)', fontsize=12)
    ax1.set_title('Time Difference vs N²\n(Linear relationship confirms O(N²) scaling)', fontsize=13)
    ax1.grid(True, alpha=0.3)

    # Plot 2: Log-log plot to extract exponent
    ax2 = axes[1]
    ax2.loglog(ctx, diff * 1000, 'o', color='#9b59b6', markersize=10, label='Measured')
    ax2.loglog(ctx, np.exp(intercept) * ctx**slope * 1000, '--',
               color='#e74c3c', linewidth=2, label=f'Fit: slope = {slope:.2f}')
    ax2.set_xlabel('Context Length (log scale)', fontsize=12)
    ax2.set_ylabel('Time Difference in ms (log scale)', fontsize=12)
    ax2.set_title(f'Log-Log Plot: Fitted Exponent = {slope:.2f}\n(2.0 = quadratic scaling)', fontsize=13)
    ax2.legend(fontsize=11)
    ax2.grid(True, alpha=0.3, which='both')

    plt.tight_layout()
    plt.savefig('kv_cache_scaling.png', dpi=150, bbox_inches='tight')
    plt.show()

    print(f"\nFitted scaling exponent: {slope:.2f}")
    print(f"(2.0 would indicate perfect O(N²) scaling of the difference)")

def main():
    # Model configuration (similar to a small-medium transformer)
    d_model = 1024
    n_heads = 16
    batch_size = 1
    num_runs = 3  # Average over multiple runs for stability

    # Context lengths to benchmark
    # Adjust these based on your GPU memory (T4 has 16GB)
    context_lengths = [128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768, 65536]

    print("=" * 60)
    print("KV Cache Benchmark: torch.cat vs Pre-allocated Buffers")
    print("=" * 60)
    print(f"Config: d_model={d_model}, n_heads={n_heads}, batch_size={batch_size}")
    print(f"Context lengths: {context_lengths}")
    print(f"Averaging over {num_runs} runs per configuration")
    print("=" * 60 + "\n")

    cat_times, prealloc_times = run_benchmark(
        context_lengths=context_lengths,
        d_model=d_model,
        n_heads=n_heads,
        batch_size=batch_size,
        num_runs=num_runs
    )

    print("\n" + "=" * 60)
    print("Summary")
    print("=" * 60)
    for ctx, t_cat, t_pre in zip(context_lengths, cat_times, prealloc_times):
        speedup = t_cat / t_pre
        print(f"Context {ctx:5d}: torch.cat={t_cat*1000:8.2f}ms, "
              f"pre-alloc={t_pre*1000:8.2f}ms, speedup={speedup:.2f}x")

    plot_results(context_lengths, cat_times, prealloc_times, d_model, n_heads)
    plot_scaling_analysis(context_lengths, cat_times, prealloc_times)

if __name__ == "__main__":
    main()